import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.function.Function;
import java.util.stream.Collectors;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static final Path FILE = Paths.get("/Users/mrszkudi/workspace/Java/serialization", "input.txt");

    public String getGreeting() {
        return "Hello world.";
    }

    public void enumerateWords() {
        try {
            Files.readAllLines(FILE, Charset.defaultCharset()).stream()
                 .map(s -> Arrays.stream(s.split("\\PL+")).distinct()
                                 .collect(Collectors.toMap(Function.identity(), str -> Arrays.asList(1))))
            .collect(Collectors.toMap(Function.identity(), Function.identity(), (stringListMap, stringListMap2) -> {
                Map<String, List<Integer>> map = new HashMap<>(stringListMap);
            }));

//                 .flatMap(Function.identity()).;
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
